"""Game content. Edit freely to add topics, traits, admin tasks or new issues."""

TOPICS = {
    "Maths": ["Place value", "Fractions", "Decimals and percentages", "Ratio", "Algebraic notation",
              "Linear equations", "Sequences", "Straight-line graphs", "Angles", "Area and perimeter",
              "Volume", "Pythagoras", "Probability", "Averages", "Transformations", "Inequalities",
              "Simultaneous equations", "Quadratics", "Trigonometry", "Problem solving"],
    "English": ["Narrative voice", "Poetry imagery", "Poetry form", "Persuasive writing", "Speech writing",
                "Shakespeare context", "Shakespeare character", "Grammar for effect", "Punctuation",
                "Descriptive writing", "Unseen prose", "Comparing texts", "Non-fiction reading", "Letter writing",
                "Drama conventions", "Gothic fiction", "Rhetoric", "Essay structure", "Spoken language", "Exam technique"],
    "Science": ["Cells", "Microscopy", "Particles", "Atoms and elements", "The periodic table", "Forces",
                "Energy stores", "Electric circuits", "Waves", "Chemical reactions", "Acids and alkalis",
                "Photosynthesis", "Respiration", "Ecosystems", "Genetics", "Magnetism", "Space",
                "Rates of reaction", "Pressure", "Required practicals"],
    "History": ["The Norman conquest", "Medieval life", "The Black Death", "The Tudors", "The Reformation",
                "The English Civil War", "The Industrial Revolution", "Empire", "Slavery and abolition", "Suffrage",
                "Causes of WWI", "Life in the trenches", "The interwar years", "Rise of dictators", "WWII",
                "The Holocaust", "The Cold War", "Decolonisation", "Civil rights", "Source analysis"],
    "Computing": ["Algorithms", "Flowcharts", "Variables", "Selection", "Iteration", "Lists", "Functions",
                  "Binary", "Hexadecimal", "Logic gates", "Hardware", "Networks", "Cyber security", "Databases",
                  "SQL basics", "HTML", "CSS", "Debugging", "Ethics and law", "Project work"],
}

ALL_SUBJECTS = ["Maths", "English", "Science", "History", "Computing", "Geography", "Art", "PE", "Music", "French"]

FIRST_NAMES = [
    "Aiko", "Haruto", "Yui", "Sora", "Ren", "Hana", "Kaito", "Mei", "Riku", "Sakura", "Yuki", "Takumi",
    "Amara", "Chidi", "Zara", "Omar", "Layla", "Priya", "Arjun", "Mateo", "Sofia", "Lucas", "Emma", "Noah",
    "Olivia", "Liam", "Ava", "Ethan", "Mia", "Leo", "Isla", "Finn", "Ruby", "Jack", "Chloe", "Kai", "Nia",
    "Ibrahim", "Fatima", "Yusuf", "Mina", "Jin", "Seo-yeon", "Min-jun", "Wei", "Lin", "Tom├ís", "Luc├¡a",
    "Diego", "Ana", "Freya", "Oscar", "Ella", "Alfie", "Grace", "Theo", "Maya", "Elijah", "Aria", "Rohan",
    "Anika", "Kofi", "Ama", "Nico", "Esme", "Hugo", "Iris", "Sami", "Noor", "Luca",
]
SURNAMES = [
    "Tanaka", "Suzuki", "Sato", "Kobayashi", "Nakamura", "Okafor", "Mensah", "Khan", "Patel", "Singh",
    "Garcia", "Martinez", "Silva", "Smith", "Jones", "Brown", "Taylor", "Wilson", "Evans", "Thomas",
    "Roberts", "Walker", "Wright", "Hughes", "Clarke", "Chen", "Wang", "Li", "Kim", "Park", "Nguyen",
    "Ali", "Hussain", "Ahmed", "Novak", "Kowalski", "Rossi", "Murphy", "O'Brien", "Dubois", "M├╝ller", "Andersen",
]

# motivation/behaviour/wellbeing are added to starting stats; disrupt multiplies disruption odds
TRAITS = {
    "Gifted":        {"desc": "Picks things up fast and gets bored easily."},
    "Class clown":   {"behaviour": -18, "disrupt": 2.2, "desc": "Lives for an audience."},
    "Anxious":       {"wellbeing": -10, "desc": "Worries about tests; exam scores drop under stress."},
    "Chatterbox":    {"behaviour": -8, "disrupt": 1.6, "desc": "Never stops talking, especially in group work."},
    "Quiet":         {"behaviour": 8, "disrupt": 0.3, "desc": "Rarely speaks up; gets less out of group work."},
    "Helpful":       {"behaviour": 12, "motivation": 5, "disrupt": 0.4, "desc": "First to hand out the books."},
    "Rebel":         {"behaviour": -15, "motivation": -12, "disrupt": 1.8, "desc": "Questions every rule."},
    "Night owl":     {"attendance": -0.05, "motivation": -5, "desc": "Often late, often yawning."},
    "Sporty":        {"motivation": -3, "desc": "Would rather be on the field."},
    "EAL":           {"desc": "English is an additional language; long explanations land less well."},
    "Perfectionist": {"motivation": 10, "wellbeing": -5, "desc": "High standards, high stress."},
    "Bookworm":      {"motivation": 10, "behaviour": 5, "disrupt": 0.5, "desc": "Reads under the desk."},
    "Hands-on":      {"desc": "Learns best by doing; switches off in long lectures."},
}

# (title, effort points, kind)  kind: parent tasks help parent rep, data tasks help leadership rep
ADMIN_TASKS = [
    ("Reply to a parent email about {student}", 1, "parent"),
    ("Update the seating plan for {cls}", 1, "admin"),
    ("Enter homework data for {cls}", 2, "data"),
    ("Complete a safeguarding training module", 3, "admin"),
    ("Order classroom supplies", 1, "admin"),
    ("Write support notes for {student}", 2, "admin"),
    ("Write up department meeting minutes", 2, "admin"),
    ("Update the behaviour log", 1, "data"),
    ("Moderate a colleague's marking", 3, "admin"),
    ("Fill in a leadership survey", 1, "data"),
    ("Set cover work for next week", 2, "admin"),
    ("Call home about {student}'s attendance", 2, "parent"),
    ("Tutor group attendance follow-up", 1, "admin"),
    ("Update the scheme of work for {cls}", 3, "admin"),
]

# Each choice has outcomes: (weight, effects, message). "skill": True means a rested,
# experienced teacher is more likely to get the first outcome.
# Effects: energy, stress, rep_students, rep_parents, rep_leadership, admin (+admin_title,
# admin_kind), plans, s_motivation, s_behaviour, s_wellbeing, s_gain, c_climate,
# c_motivation, detention, followup (+followup_in), cover, observe, zero_test, tone.
EVENTS = {
    "disruption": {
        "title": "{first} is disrupting {cls}",
        "text": "{name} keeps talking over you, and the rest of the class is starting to join in.",
        "choices": {
            "warn": {"label": "Give a clear warning", "hint": "Quick. Might not land.",
                     "outcomes": [(0.6, {"s_behaviour": 3, "tone": 1}, "{first} settled down after a warning."),
                                  (0.4, {"c_climate": -3, "s_behaviour": -2, "tone": -1}, "The warning didn't land. {first} kept going and {cls} got noisier.")]},
            "detention": {"label": "Set a detention", "hint": "Needs supervising at lunch.",
                          "outcomes": [(1, {"detention": True, "s_behaviour": 2, "s_motivation": -4, "admin": 1,
                                            "admin_title": "Log a detention on the system"},
                                        "Detention set for {first}. Supervise detentions at lunch to make it stick.")]},
            "redirect": {"label": "Give them a job to do", "hint": "Works better when you have energy.", "skill": True,
                         "outcomes": [(0.55, {"energy": -3, "s_motivation": 6, "s_behaviour": 5, "rep_students": 1, "tone": 1},
                                       "{first} handed out resources and was brilliant for the rest of the lesson."),
                                      (0.45, {"energy": -3, "c_climate": -2, "tone": -1}, "{first} treated the job as a stage. Worth a try.")]},
            "ignore": {"label": "Carry on teaching", "hint": "Tactical ignoring. Risky.",
                       "outcomes": [(0.3, {}, "It fizzled out on its own."),
                                    (0.7, {"c_climate": -5, "s_behaviour": -4, "tone": -1}, "Ignoring it made it worse. {cls} learned that anything goes.")]},
        },
    },
    "phone": {
        "title": "{first} is on their phone",
        "text": "You spot {name} scrolling under the desk during your explanation.",
        "choices": {
            "confiscate": {"label": "Confiscate it to the office", "hint": "School policy.",
                           "outcomes": [(0.8, {"s_behaviour": 3, "s_motivation": -3, "admin": 1, "admin_title": "Log a confiscated phone", "tone": 1},
                                         "Phone confiscated. {first} sulked but the class noticed you follow through."),
                                        (0.2, {"s_behaviour": -6, "followup": "parent_complaint", "tone": -1},
                                         "{first} refused to hand it over and stormed out. Expect an email from home.")]},
            "warn": {"label": "Ask them to put it away", "hint": "Low key.",
                     "outcomes": [(0.65, {"tone": 1}, "Phone away. Lesson carried on."),
                                  (0.35, {"c_climate": -2, "tone": -1}, "It was back out five minutes later.")]},
            "ignore": {"label": "Pretend you didn't see", "hint": "Saves a battle today.",
                       "outcomes": [(1, {"c_climate": -3, "s_motivation": -2, "tone": -1}, "Three more phones appeared by the end of the lesson.")]},
        },
    },
    "defiance": {
        "title": "{first} refuses to work",
        "text": "{name} has pushed the worksheet away. \"This is pointless,\" loud enough for everyone to hear.",
        "choices": {
            "talk": {"label": "Quiet word at their desk", "hint": "Relationship first.", "skill": True,
                     "outcomes": [(0.6, {"energy": -3, "s_motivation": 7, "s_behaviour": 3, "tone": 1},
                                   "You found out {first} was lost from the first step. Ten minutes later they were working."),
                                  (0.4, {"energy": -3, "s_behaviour": -2, "tone": -1}, "{first} shrugged you off.")]},
            "send_out": {"label": "Send them to the Head of Department", "hint": "Protects the lesson.",
                         "outcomes": [(1, {"c_climate": 3, "rep_leadership": -1, "s_motivation": -5}, "{first} was removed. The rest of {cls} got on with it.")]},
            "call_home": {"label": "Phone home after school", "hint": "Admin, but often effective.",
                          "outcomes": [(0.75, {"admin": 2, "admin_kind": "parent", "admin_title": "Phone call home about behaviour",
                                               "s_behaviour": 8, "rep_parents": 1, "tone": 1}, "A supportive parent. {first} arrived next lesson ready to work."),
                                       (0.25, {"admin": 2, "admin_kind": "parent", "admin_title": "Phone call home about behaviour",
                                               "rep_parents": -2, "tone": -1}, "The parent sided with {first}. Awkward.")]},
        },
    },
    "sick_student": {
        "title": "{first} feels unwell",
        "text": "{name} looks pale and asks to leave the room.",
        "choices": {
            "nurse": {"label": "Send them to the medical room", "hint": "Safe choice.",
                      "outcomes": [(1, {"s_wellbeing": 4, "tone": 1}, "{first} went home early and is fine.")]},
            "stay": {"label": "Ask them to sit near the door", "hint": "They might be fine.",
                     "outcomes": [(0.6, {}, "{first} perked up by the end of the lesson."),
                                  (0.4, {"s_wellbeing": -6, "rep_parents": -3, "tone": -1}, "{first} was sick in the corridor. A parent has complained.")]},
        },
    },
    "cheating": {
        "title": "{first} copied in the quiz",
        "text": "While collecting scripts you notice {name}'s answers match their neighbour's, word for word.",
        "choices": {
            "void": {"label": "Void the quiz score", "hint": "Firm and fair.",
                     "outcomes": [(0.7, {"zero_test": True, "s_behaviour": 3, "s_motivation": -4, "tone": 1}, "Score voided. {first} got the message."),
                                  (0.3, {"zero_test": True, "followup": "parent_complaint", "tone": -1}, "Score voided. {first}'s parent is unhappy about it.")]},
            "talk": {"label": "Have a word, keep the score", "hint": "Second chance.",
                     "outcomes": [(1, {"s_motivation": 2, "c_climate": -2}, "{first} promised it won't happen again. Others noticed there was no consequence.")]},
            "report": {"label": "Report it to the Head of Department", "hint": "By the book.",
                       "outcomes": [(1, {"zero_test": True, "admin": 1, "admin_title": "Academic misconduct form", "rep_leadership": 1, "s_motivation": -5},
                                     "Reported and logged.")]},
        },
    },
    "corridor_fight": {
        "title": "Scuffle on the playground",
        "text": "During duty you see {name} from {cls} in a shoving match that's drawing a crowd.",
        "priority": 2,
        "choices": {
            "intervene": {"label": "Step in and separate them", "hint": "Tiring, but decisive.",
                          "outcomes": [(1, {"energy": -6, "rep_students": 1, "s_behaviour": 3, "admin": 1, "admin_title": "Write an incident report", "tone": 1},
                                        "You calmed it down before anyone got hurt.")]},
            "radio": {"label": "Radio for senior staff", "hint": "Safe and by the book.",
                      "outcomes": [(1, {"rep_leadership": -1, "admin": 1, "admin_title": "Witness statement"}, "Senior staff took over.")]},
            "disperse": {"label": "Just move the crowd on", "hint": "Doesn't deal with the cause.",
                         "outcomes": [(0.5, {}, "It broke up."), (0.5, {"s_behaviour": -5, "s_wellbeing": -5, "rep_leadership": -3, "tone": -1},
                                                                  "It flared up again after lunch. Leadership asked why it wasn't reported.")]},
        },
    },
    "parent_complaint": {
        "title": "Email from {first}'s parent",
        "text": "{name}'s parent has emailed, unhappy about their child's progress in {cls} and asking what you're doing about it.",
        "choices": {
            "call": {"label": "Phone them today", "hint": "Draining but builds trust.", "skill": True,
                     "outcomes": [(0.75, {"energy": -8, "rep_parents": 5, "s_motivation": 3, "tone": 1}, "A good conversation. {first}'s parent is now on side."),
                                  (0.25, {"energy": -8, "stress": 5, "rep_parents": 1}, "A long, tense call. You got through it.")]},
            "email": {"label": "Reply by email", "hint": "Adds to admin.",
                      "outcomes": [(1, {"admin": 1, "admin_kind": "parent", "admin_title": "Detailed reply to a parent", "rep_parents": 1}, "Reply added to your admin list.")]},
            "forward": {"label": "Forward to the Head of Department", "hint": "Passes the problem up.",
                        "outcomes": [(1, {"rep_leadership": -2, "rep_parents": 1}, "Your Head of Department handled it, with a sigh.")]},
            "ignore": {"label": "Leave it for now", "hint": "It may escalate.",
                       "outcomes": [(1, {"rep_parents": -4, "followup": "parent_escalation", "followup_in": 2, "tone": -1}, "The email sits unanswered.")]},
        },
    },
    "parent_escalation": {
        "title": "Meeting with {deputy}",
        "text": "{name}'s parent went over your head. The Deputy Head wants a meeting about it.",
        "priority": 2, "staff": 1, "mood": "angry",
        "choices": {
            "evidence": {"label": "Bring marked work and data", "hint": "Better if your marking is up to date.", "skill": True,
                         "outcomes": [(0.6, {"energy": -6, "rep_leadership": 2, "rep_parents": 3, "tone": 1}, "Your evidence settled it."),
                                      (0.4, {"energy": -6, "rep_leadership": -4, "stress": 6, "tone": -1}, "The gaps in your records didn't look good.")]},
            "apologise": {"label": "Apologise and agree a plan", "hint": "Adds follow-up work.",
                          "outcomes": [(1, {"energy": -4, "rep_parents": 4, "rep_leadership": -1, "admin": 3, "admin_kind": "parent",
                                            "admin_title": "Weekly progress updates to a parent"}, "Agreed weekly updates with home.")]},
        },
    },
    "safeguarding": {
        "title": "{first} seems withdrawn",
        "text": "{name} has been quiet and tearful all week and mentioned things being difficult at home.",
        "priority": 3,
        "choices": {
            "log": {"label": "Log it with {dsl} (safeguarding lead)", "hint": "Always the right first step.",
                    "outcomes": [(1, {"admin": 2, "admin_title": "Safeguarding log entry", "s_wellbeing": 12, "rep_leadership": 2, "tone": 1},
                                  "Concern logged. Pastoral staff are now supporting {first}.")]},
            "talk": {"label": "Talk to them yourself", "hint": "Kind, but concerns must be logged.",
                     "outcomes": [(0.5, {"energy": -6, "s_wellbeing": 6}, "{first} opened up a little. You made a note."),
                                  (0.5, {"energy": -6, "s_wellbeing": 4, "rep_leadership": -7, "tone": -1},
                                   "The safeguarding lead found out later that you hadn't logged it. Serious conversation.")]},
            "ignore": {"label": "Keep an eye on it", "hint": "Not appropriate for a safeguarding concern.",
                       "outcomes": [(1, {"s_wellbeing": -10, "rep_leadership": -12, "stress": 8, "tone": -1},
                                     "It came out later through another route. Leadership asked why you didn't report it.")]},
        },
    },
    "homework": {
        "title": "Missing homework in {cls}",
        "text": "Half of {cls} didn't hand in homework, including {name} for the third time.",
        "choices": {
            "chase": {"label": "Email home for the worst offenders", "hint": "Admin load.",
                      "outcomes": [(1, {"admin": 2, "admin_kind": "parent", "admin_title": "Homework emails home", "c_motivation": 2, "tone": 1}, "Emails queued. Homework rates should pick up.")]},
            "sanction": {"label": "Detention for {first}", "hint": "Sets a standard.",
                         "outcomes": [(1, {"detention": True, "c_climate": 2, "c_motivation": -2}, "{first} has a detention. The class noticed.")]},
            "redesign": {"label": "Redesign homework to be shorter", "hint": "Costs a lesson plan.",
                         "outcomes": [(1, {"plans": -1, "c_motivation": 3, "tone": 1}, "Shorter, sharper homework. {cls} seem keener.")]},
            "let_go": {"label": "Let it slide this time", "hint": "Easy today, harder later.",
                       "outcomes": [(1, {"c_motivation": -3, "tone": -1}, "Next week even fewer handed it in.")]},
        },
    },
    "extra_help": {
        "title": "{first} asks for extra help",
        "text": "{name} catches you after the lesson: \"I don't get any of it. Can you go over it again?\"",
        "choices": {
            "session": {"label": "Stay after school with them", "hint": "Real progress, costs energy.",
                        "outcomes": [(1, {"energy": -8, "s_gain": 0.25, "s_motivation": 8, "rep_students": 1, "tone": 1}, "Forty minutes later, it clicked for {first}.")]},
            "resources": {"label": "Send some resources", "hint": "Quick.",
                          "outcomes": [(1, {"admin": 1, "admin_title": "Send revision resources", "s_gain": 0.08, "s_motivation": 2}, "Resources sent.")]},
            "later": {"label": "Not this week, sorry", "hint": "You're stretched.",
                      "outcomes": [(1, {"s_motivation": -5, "tone": -1}, "{first} looked crestfallen.")]},
        },
    },
    "bored_gifted": {
        "title": "{first} is coasting",
        "text": "{name} finishes everything in five minutes and has started distracting others.",
        "choices": {
            "extend": {"label": "Plan extension tasks", "hint": "Uses a lesson plan.",
                       "outcomes": [(1, {"plans": -1, "s_motivation": 8, "s_gain": 0.12, "tone": 1}, "{first} loved the challenge.")]},
            "helper": {"label": "Make them a peer helper", "hint": "Free, sometimes brilliant.",
                       "outcomes": [(0.7, {"s_motivation": 4, "c_climate": 2, "tone": 1}, "{first} is a natural at explaining."),
                                    (0.3, {"s_motivation": -2}, "{first} got bored of helping too.")]},
            "leave": {"label": "They're fine, they'll get an A", "hint": "Hmm.",
                      "outcomes": [(1, {"s_motivation": -6, "s_behaviour": -4, "tone": -1}, "{first} is turning into a distraction.")]},
        },
    },
    "thank_you": {
        "title": "A note from {first}",
        "text": "You find a folded note on your desk from {name}: \"Thanks for not giving up on me.\"",
        "choices": {
            "keep": {"label": "Keep it in your desk drawer", "hint": "",
                     "outcomes": [(1, {"stress": -8, "energy": 4, "tone": 1}, "That one's going in the drawer for bad days.")]},
        },
    },
    "data_deadline": {
        "title": "Data drop from {deputy}",
        "text": "Leadership want predicted grades and intervention notes for every class by the end of the week.",
        "staff": 1,
        "choices": {
            "now": {"label": "Do it tonight", "hint": "Tiring but done.",
                    "outcomes": [(1, {"energy": -7, "rep_leadership": 3, "tone": 1}, "Submitted early. Leadership noticed.")]},
            "list": {"label": "Add it to your list", "hint": "Due in a few days.",
                     "outcomes": [(1, {"admin": 4, "admin_kind": "data", "admin_title": "Predicted grades data drop"}, "Added to your admin list.")]},
            "push": {"label": "Ask for an extension", "hint": "They might say no.",
                     "outcomes": [(0.5, {"stress": -2}, "Extension granted."),
                                  (0.5, {"rep_leadership": -3, "admin": 4, "admin_kind": "data", "admin_title": "Predicted grades data drop", "tone": -1},
                                   "Extension refused, and now you look disorganised.")]},
        },
    },
    "cover_request": {
        "title": "Cover needed tomorrow",
        "text": "{colleague} is off sick tomorrow. Can you cover a lesson in one of your free periods?",
        "staff": 1,
        "choices": {
            "accept": {"label": "Accept the cover", "hint": "Lose a free period tomorrow.",
                       "outcomes": [(1, {"cover": True, "rep_leadership": 2, "tone": 1}, "Cover added to tomorrow's timetable.")]},
            "decline": {"label": "Decline politely", "hint": "Leadership may not like it.",
                        "outcomes": [(0.5, {}, "Someone else took it."), (0.5, {"rep_leadership": -3, "tone": -1}, "The cover manager was not impressed.")]},
        },
    },
    "observation": {
        "title": "{hod} will observe you tomorrow",
        "text": "Your Head of Department is dropping into your lesson with {cls} tomorrow. Avoid the film.",
        "staff": 0,
        "choices": {
            "noted": {"label": "Noted", "hint": "Teach as planned.",
                      "outcomes": [(1, {"observe": True, "stress": 3}, "Observation booked for {cls} tomorrow.")]},
            "prep": {"label": "Spend the evening planning something special", "hint": "+2 plans for that class, costs energy.",
                     "outcomes": [(1, {"observe": True, "plans": 2, "energy": -7, "stress": 2}, "Observation booked. Your {cls} lesson is polished.")]},
        },
    },
    "anxious_exam": {
        "title": "{first} is panicking about exams",
        "text": "{name} is in tears before registration: \"I'm going to fail everything.\"",
        "choices": {
            "reassure": {"label": "Reassure them and make a revision plan", "hint": "Costs a little energy.",
                         "outcomes": [(1, {"energy": -4, "s_wellbeing": 12, "tone": 1}, "{first} left with a plan and a bit more confidence.")]},
            "papers": {"label": "Give them past papers", "hint": "Practical.",
                       "outcomes": [(1, {"s_gain": 0.1, "s_wellbeing": 3}, "Past papers handed over.")]},
            "refer": {"label": "Refer them to pastoral", "hint": "Adds admin.",
                      "outcomes": [(1, {"admin": 1, "admin_title": "Pastoral referral form", "s_wellbeing": 7}, "Pastoral team are checking in on {first}.")]},
        },
    },
    "colleague_favour": {
        "title": "{colleague} asks a favour",
        "text": "\"Could you take my duty on Friday? I'll owe you one.\"",
        "staff": 3,
        "choices": {
            "yes": {"label": "Sure", "hint": "Costs energy.",
                    "outcomes": [(1, {"energy": -6, "rep_leadership": 1, "stress": -1, "tone": 1}, "Good karma banked.")]},
            "no": {"label": "Sorry, I'm swamped", "hint": "",
                   "outcomes": [(1, {}, "They understood.")]},
        },
    },
    "trip_request": {
        "title": "Trip idea for {cls}?",
        "text": "A local museum has a free workshop slot that fits your topic. You'd need to do the risk assessment and permission slips.",
        "choices": {
            "organise": {"label": "Organise it", "hint": "Big admin job, big payoff.",
                         "outcomes": [(1, {"admin": 4, "admin_title": "Trip risk assessment and permission slips", "c_motivation": 8,
                                           "rep_parents": 2, "rep_students": 3, "tone": 1}, "Trip booked. {cls} are buzzing.")]},
            "decline": {"label": "Not this term", "hint": "",
                        "outcomes": [(1, {}, "Maybe next term.")]},
        },
    },
}
